---
- name: Configure and update sudo specs files
  template:
    src: 'sudoers_spec.j2'
    dest: '{{ sudo__confd_dir }}/{{ item.name }}'
    owner: 'root'
    group: 'root'
    mode: 0440
    validate: 'visudo -cf %s'
  with_items: '{{ sudo__specs }}'
  when: ((item.name is defined and item.name|trim) and
         (item.disabled is undefined or not item.disabled|bool) and
         (item.defaults is defined or item.specs is defined))

- name: Remove sudo specs files
  file:
    path: '{{ sudo__confd_dir }}/{{ item.name }}'
    state: 'absent'
  with_items: '{{ sudo__specs }}'
  when: ((item.name is defined and item.name|trim) and
         (item.disabled is defined and item.disabled|bool))

- include: 'purge-unmanaged-specs.yml'
  when: (sudo__specs_purge_unmanaged|bool)

- name: Configure and update defaults and aliases in sudoers file
  template:
    src: 'sudoers.j2'
    dest: '{{ sudo__conf_file }}'
    owner: 'root'
    group: 'root'
    mode: 0440
    validate: 'visudo -cf %s'
