---
- name: Initialize - Include OS specific variables
  include_vars: "os/{{ ansible_os_family }}.yml"
  tags: [ "always" ]

- name: Setup sudo
  include: "setup/main.yml"
  tags: [ "setup" ]

- name: Configure sudo
  include: "configure/main.yml"
  tags: [ "configure" ]
